name: lint-and-test
on:
  push:
    branches: ["*"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      - name: Check formatting
        run: black --check .
      - name: Lint code
        run: pylint src/*
      - name: Run unit tests
        run: |
          PYTHONPATH="${PYTHON_PATH}:./src" python -m pytest -v tests/unit

      - name: Run functional test
        run: |
          PYTHONPATH="${PYTHON_PATH}:./src" python -m pytest -v tests/functional
      - name: Run coverage
        run: |
          PYTHONPATH="${PYTHON_PATH}:./src" coverage run -m pytest -v tests/unit tests/functional
      - name: Generate coverage report
        run: |
          coverage report -m
