name: lint-and-test
on:
  push:
    branches: ["*"]

env:
  SETUP_PYTHON_VERSION: '3.8'
  NODE_VERSION: '16.x'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.SETUP_PYTHON_VERSION }}
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check formatting
        run: black --check .
      - name: Lint code
        run: pylint src/*
      - name: Lint tests
        run: pylint tests/*
      - name: Run tests
        run: pytest --cov=src tests/

